# Generated by Django 2.0 on 2021-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
